//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitySqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string rif { get; set; }
        public string clave1 { get; set; }
        public string clave2 { get; set; }
        public string clave3 { get; set; }
        public string telefono { get; set; }
        public string sucursal { get; set; }
        public string codigo_sucursal { get; set; }
        public string nit { get; set; }
        public string contacto { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string registro { get; set; }
        public string Telefono_1 { get; set; }
        public string Telefono_2 { get; set; }
        public string Telefono_3 { get; set; }
        public string Telefono_4 { get; set; }
        public string Celular_1 { get; set; }
        public string Celular_2 { get; set; }
        public string Fax_1 { get; set; }
        public string Fax_2 { get; set; }
        public string Direccion_Referencia { get; set; }
        public byte[] Id_Seguridad { get; set; }
    }
}
