//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_medio_pago
    {
        public string auto_recibo { get; set; }
        public string auto_medio_pago { get; set; }
        public string auto_agencia { get; set; }
        public string medio { get; set; }
        public string codigo { get; set; }
        public decimal monto_recibido { get; set; }
        public System.DateTime fecha { get; set; }
        public string estatus_anulado { get; set; }
        public string numero { get; set; }
        public string agencia { get; set; }
        public string auto_usuario { get; set; }
        public string lote { get; set; }
        public string referencia { get; set; }
        public string auto_cobrador { get; set; }
        public string cierre { get; set; }
        public System.DateTime fecha_agencia { get; set; }
        public string cierre_ftp { get; set; }
        public string opBanco { get; set; }
        public string opNroCta { get; set; }
        public string opNroRef { get; set; }
        public Nullable<System.DateTime> opFecha { get; set; }
        public string opDetalle { get; set; }
        public decimal opMonto { get; set; }
        public decimal opTasa { get; set; }
        public string opAplicaConversion { get; set; }
        public string estatus_doc_cxc { get; set; }
        public string codigo_sucursal { get; set; }
    }
}
