//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_movimientos_transito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos_movimientos_transito()
        {
            this.productos_movimientos_transito_detalle = new HashSet<productos_movimientos_transito_detalle>();
        }
    
        public int id { get; set; }
        public string idSucOrigen { get; set; }
        public string idSucDestino { get; set; }
        public string idDepOrigen { get; set; }
        public string idDepDestino { get; set; }
        public string idConcepto { get; set; }
        public System.DateTime fecha { get; set; }
        public string autoriza { get; set; }
        public string motivo { get; set; }
        public decimal monto { get; set; }
        public decimal montoDivisa { get; set; }
        public decimal factorCambio { get; set; }
        public int cntRenglones { get; set; }
        public string codigoMov { get; set; }
        public string tipoMov { get; set; }
        public string desMov { get; set; }
        public string desSucOrigen { get; set; }
        public string desSucDestino { get; set; }
        public string desDepOrigen { get; set; }
        public string desDepDestino { get; set; }
        public string desConcepto { get; set; }
        public string desUsuario { get; set; }
        public string estacionEquipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_movimientos_transito_detalle> productos_movimientos_transito_detalle { get; set; }
    }
}
