//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_movimientos_detalle
    {
        public string auto_documento { get; set; }
        public string auto_producto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public decimal cantidad { get; set; }
        public decimal cantidad_bono { get; set; }
        public decimal cantidad_und { get; set; }
        public string categoria { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo { get; set; }
        public string estatus_anulado { get; set; }
        public int contenido_empaque { get; set; }
        public string empaque { get; set; }
        public string decimales { get; set; }
        public string auto { get; set; }
        public decimal costo_und { get; set; }
        public decimal total { get; set; }
        public decimal costo_compra { get; set; }
        public string estatus_unidad { get; set; }
        public int signo { get; set; }
        public decimal existencia { get; set; }
        public decimal fisica { get; set; }
        public string auto_departamento { get; set; }
        public string auto_grupo { get; set; }
        public string cierre_ftp { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual productos_movimientos productos_movimientos { get; set; }
    }
}
