//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_movimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos_movimientos()
        {
            this.productos_movimientos_detalle = new HashSet<productos_movimientos_detalle>();
        }
    
        public string auto { get; set; }
        public string documento { get; set; }
        public System.DateTime fecha { get; set; }
        public string nota { get; set; }
        public string estatus_anulado { get; set; }
        public string usuario { get; set; }
        public string codigo_usuario { get; set; }
        public string hora { get; set; }
        public string estacion { get; set; }
        public string concepto { get; set; }
        public string auto_concepto { get; set; }
        public string codigo_concepto { get; set; }
        public string auto_usuario { get; set; }
        public string auto_deposito { get; set; }
        public string codigo_deposito { get; set; }
        public string deposito { get; set; }
        public string auto_destino { get; set; }
        public string codigo_destino { get; set; }
        public string destino { get; set; }
        public string tipo { get; set; }
        public int renglones { get; set; }
        public string documento_nombre { get; set; }
        public string autorizado { get; set; }
        public decimal total { get; set; }
        public string estatus_cierre_contable { get; set; }
        public string situacion { get; set; }
        public string auto_remision { get; set; }
        public string codigo_sucursal { get; set; }
        public string cierre_ftp { get; set; }
    
        public virtual empresa_depositos empresa_depositos { get; set; }
        public virtual empresa_depositos empresa_depositos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_movimientos_detalle> productos_movimientos_detalle { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual productos_conceptos productos_conceptos { get; set; }
    }
}
