//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_precios_ext
    {
        public int id { get; set; }
        public int id_producto_precio { get; set; }
        public string empaque { get; set; }
        public int contenido { get; set; }
    }
}
