//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_movimientos_extra
    {
        public int id { get; set; }
        public string auto_movimiento { get; set; }
        public decimal factor_cambio { get; set; }
        public decimal monto_divisa { get; set; }
    }
}
